name: 'Lint Code'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Print working directory
      run: pwd

    - name: Run Python Linter
      run: |
        echo "Linting Python files..."
        flake8 .  # Runs flake8 on all Python files in the repo
        echo "Linted all Python files successfully"

  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Go to package.json
      run: cd ./server

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Install ESLint (optional, if you want to switch from JSHint to ESLint)
      run: npm install eslint --global

    - name: Run JavaScript Linter
      run: |
        echo "Linting JavaScript files..."
        # You can replace this with ESLint for more modern linting
        eslint ./server/database/**/*.js  # Lint all JS files in server/database directory
        echo "Linted all JavaScript files successfully"
